# coding=utf-8
# [card, row, strength, ability]

nr_cards = [
	['Biting Frost', 0, 0, 5],
	['Biting Frost', 0, 0, 5],
	['Redanian Foot Soldier', 0, 1, None],
	['Redanian Foot Soldier', 0, 1, None],
	['Poor Fucking Infantry', 0, 1, 0],
	['Poor Fucking Infantry', 0, 1, 0],
	['Poor Fucking Infantry', 0, 1, 0],
	['Yarpen Zigrin', 0, 2, None],
	['Blue Stripes Commando', 0, 4, 0],
	['Blue Stripes Commando', 0, 4, 0],
	['Blue Stripes Commando', 0, 4, 0],
	['Sigismund Dijkstra', 0, 4, 1],
	['Ves', 0, 5, None],
	['Siegfried of Denesle', 0, 5, None],
	['Prince Stennis', 0, 5, 1],
	['Esterad Thyssen', 0, 10, 2],
	['John Natalis', 0, 10, 2],
	['Vernon Roche', 0, 10, 2],

	['Impenetrable Fog', 1, 0, 5],
	['Impenetrable Fog', 1, 0, 5],
	['Sabrina Glevissig', 1, 4, None],
	['Sheldon Skaggs', 1, 4, None],
	['Sile de Tansarville', 1, 5, None],
	['Crinfrid Reavers Dragon Hunter', 1, 5, 0],
	['Crinfrid Reavers Dragon Hunter', 1, 5, 0],
	['Crinfrid Reavers Dragon Hunter', 1, 5, 0],
	['Keira Metz', 1, 5, None],
	['Dethmold', 1, 6, None],
	['Philippa Eilhart', 1, 10, 2],

	['Torrential Rain', 2, 0, 5],
	['Torrential Rain', 2, 0, 5],
	['Kaedweni Siege Expert', 2, 1, 3],
	['Kaedweni Siege Expert', 2, 1, 3],
	['Kaedweni Siege Expert', 2, 1, 3],
	['Thaler', 2, 1, 1],
	['Dun Banner Medic', 2, 5, 4],
	['Siege Tower', 2, 6, None],
	['Trebuchet', 2, 6, None],
	['Trebuchet', 2, 6, None],
	['Ballista', 2, 6, None],
	['Ballista', 2, 6, None],
	['Catapult', 2, 8, 0],
	['Catapult', 2, 8, 0],

	['Clear Weather', 3, 0, 5],
	['Clear Weather', 3, 0, 5],
]