# coding=utf-8
# [card, row, strength, ability, affects, image]

nr_cards = [
    # ['Redanian Foot Soldier', 0, 1, 0, 0, 'northern-realms/redanian-foot-soldier.png'],
    # ['Redanian Foot Soldier', 0, 1, 0, 0, 'northern-realms/redanian-foot-soldier.png'],
    # ['Poor Fucking Infantry', 0, 1, 1, 1, 'northern-realms/poor-fucking-infantry.png'],
    # ['Poor Fucking Infantry', 0, 1, 1, 1, 'northern-realms/poor-fucking-infantry.png'],
    # ['Poor Fucking Infantry', 0, 1, 1, 1, 'northern-realms/poor-fucking-infantry.png'],
    # ['Yarpen Zigrin', 0, 2, 0, 0, 'northern-realms/yarpen-zigrin.png'],
    ['Blue Stripes Commando', 0, 4, 1, 2, 'northern-realms/blue-stripes-commando.png'],
    ['Blue Stripes Commando', 0, 4, 1, 2, 'northern-realms/blue-stripes-commando.png'],
    ['Blue Stripes Commando', 0, 4, 1, 2, 'northern-realms/blue-stripes-commando.png'],
    ['Sigismund Dijkstra', 0, 4, 2, 0, 'northern-realms/sigismund-dijkstra.png'],
    ['Ves', 0, 5, 0, 0, 'northern-realms/ves.png'],
    ['Siegfried of Denesle', 0, 5, 0, 0, 'northern-realms/siegfried-of-denesle.png'],
    ['Prince Stennis', 0, 5, 2, 0, 'northern-realms/prince-stennis.png'],
    ['Esterad Thyssen', 0, 10, 3, 0, 'northern-realms/esterad-thyssen.png'],
    ['John Natalis', 0, 10, 3, 0, 'northern-realms/john-natalis.png'],
    ['Vernon Roche', 0, 10, 3, 0, 'northern-realms/vernon-roche.png'],

    ['Sabrina Glevissig', 1, 4, 0, 0, 'northern-realms/sabrina-glevissig.png'],
    ['Sheldon Skaggs', 1, 4, 0, 0, 'northern-realms/sheldon-skaggs.png'],
    ['Sile de Tansarville', 1, 5, 0, 0, 'northern-realms/sile-de-tansarville.png'],
    ['Crinfrid Reavers Dragon Hunter', 1, 5, 1, 3, 'northern-realms/crinfrid-reavers-dragon-hunter.png'],
    ['Crinfrid Reavers Dragon Hunter', 1, 5, 1, 3, 'northern-realms/crinfrid-reavers-dragon-hunter.png'],
    ['Crinfrid Reavers Dragon Hunter', 1, 5, 1, 3, 'northern-realms/crinfrid-reavers-dragon-hunter.png'],
    ['Keira Metz', 1, 5, 0, 0, 'northern-realms/keira-metz.png'],
    ['Dethmold', 1, 6, 0, 0, 'northern-realms/dethmold.png'],
    ['Philippa Eilhart', 1, 10, 3, 0, 'northern-realms/philippa-eilhart.png'],

    # ['Kaedweni Siege Expert', 2, 1, 4, 0, 'northern-realms/kaedweni-siege-expert.png'],
    ['Kaedweni Siege Expert', 2, 1, 4, 0, 'northern-realms/kaedweni-siege-expert.png'],
    ['Kaedweni Siege Expert', 2, 1, 4, 0, 'northern-realms/kaedweni-siege-expert.png'],
    ['Thaler', 2, 1, 2, 0, 'northern-realms/thaler.png'],
    ['Dun Banner Medic', 2, 5, 5, 0, 'northern-realms/dun-banner-medic.png'],
    ['Siege Tower', 2, 6, 0, 0, 'northern-realms/siege-tower.png'],
    ['Trebuchet', 2, 6, 0, 0, 'northern-realms/trebuchet.png'],
    ['Trebuchet', 2, 6, 0, 0, 'northern-realms/trebuchet.png'],
    ['Ballista', 2, 6, 0, 0, 'northern-realms/ballista.png'],
    ['Ballista', 2, 6, 0, 0, 'northern-realms/ballista.png'],
    ['Catapult', 2, 8, 1, 4, 'northern-realms/catapult.png'],
    ['Catapult', 2, 8, 1, 4, 'northern-realms/catapult.png'],

    ['Biting Frost', 0, 0, 6, 0, 'neutral/biting-frost.png'],
    # ['Biting Frost', 0, 0, 6, 0, 'neutral/biting-frost.png'],
    ['Impenetrable Fog', 1, 0, 6, 0, 'neutral/impenetrable-fog.png'],
    # ['Impenetrable Fog', 1, 0, 6, 0, 'neutral/impenetrable-fog.png'],
    ['Torrential Rain', 2, 0, 6, 0, 'neutral/torrential-rain.png'],
    # ['Torrential Rain', 2, 0, 6, 0, 'neutral/torrential-rain.png'],
    ['Clear Weather', 3, 0, 6, 0, 'neutral/clear-weather.png'],
    # ['Clear Weather', 3, 0, 6, 0, 'neutral/clear-weather.png'],
    ['Scorch', 3, 0, 7, 0, 'neutral/scorch.png'],
    ['Scorch', 3, 0, 7, 0, 'neutral/scorch.png'],
]
